---
# Install/run influxdb
- name: "[Influxdb] Install influxdb"
  yum:
    name: influxdb
    state: present
  become: true

- name: "[Influxdb] Copy templated influxdb.conf"
  template:
    src: "influxdb.conf.j2"
    dest: "/etc/influxdb/influxdb.conf"
    mode: 0644
  become: true

- name: "[Influxdb] Enable Influxdb on boot"
  systemd:
    name: influxd
    state: started
    enabled: true
  become: true
