# SETUP AGENT
- name: Copy templated influxdb.repo
  template:
    src: influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    mode: 0644
  become: true

  #FIREWALL TASKS
- name: check if firewalld exists
  stat:
    path: /etc/sysconfig/firewalld
  register: firewall_rules


- name: "[Telegraf] ADD FIREWALLD TCP PORT {{ telegraf_port }}"
  firewalld:
   port: "{{ telegraf_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true
  when: "firewall_rules.stat.exists == true"
# END telegraf FIREWALLD PORT

- name: "[Telegraf] ADD FIREWALLD TCP PORT {{ telegraf_port }}"
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: "{{ telegraf_port }}"
  when: "firewall_rules.stat.exists == false"

# INSTALL TELEGRAF
- name: "[Telegraf] Install telegraf"
  yum:
    name: telegraf
    state: present
  become: true

- name: "[Telegraf] Copy templated telegraf.yml"
  template:
    src: "agent.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    mode: 0644
  become: true

- name: "[Telegraf] Setup telegraf service to autostart"
  systemd:
    name: telegraf
    state: restarted
    enabled: true
  become: true
