---

# Install/run telegraf agent on remote host
- name: Copy templated influxdb.repo
  template:
    src: influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    mode: 0644
  become: true

- name: Install dependancies
  package:
    name: [mailx, tcl, python2-toml, python36-toml, python-pytoml]
    state: present
  become: true

# Install and configure telegraf
- name: "[Telegraf] Install telegraf"
  yum:
    name: telegraf
    state: present
  become: true

- name: "[Telegraf] Copy templated telegraf agent.conf"
  template:
    src: "agent.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    mode: 0644
  become: true

- name: "[influxdb] ADD FIREWALLD TCP PORT {{ influxdb_port }}"
  firewalld:
   port: "{{ influxdb_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true

- name: "[Chronograf] ADD FIREWALLD TCP PORT {{ chronograf_port }}"
  firewalld:
   port: "{{ chronograf_port }}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true

- name: "[Telegraf] Setup telegraf service to autostart"
  systemd:
    name: telegraf
    state: started
    enabled: true
  become: true

- name: RELOAD FIREWALLD
  systemd:
    name: firewalld
    state: reloaded
  become: true
