---
- name: Download grafana
  get_url:
    url: "{{ grafana_url }}"
    dest: /tmp/
    force_basic_auth: yes

- name: "[Grafana] Install grafana"
  yum:
    name: "/tmp/{{ grafana_rpm }}"
    state: present
  become: true

- name: "[Grafana] Copy grafana template"
  template:
    src: "{{ item }}"
    dest: "{{ grafana_conf_dir }}/{{ item | basename | regex_replace('.j2','')}}"
  become: true
  with_items:
    - "grafana.ini.j2"

- name: "[Grafana] Enable Grafana service on boot"
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: true

- name: "[Grafana] Start Grafana service"
  service:
    name: Grafana-server
    state: started
  become: true
